# Destroy Resource Group 
stages:
- stage: PulumiPreviewResourceGroup
  jobs:
    - job: InfraStack
      pool:
        vmImage: "ubuntu-latest"
        variables:
        - name: mysubrcription
          value: $(AZURE_SUBSCRIPTION) 
      steps:
        - bash: export PULUMI_CONFIG_PASSPHRASE=$(PULUMI_CONFIG_PASSPHRASE)
        - bash: export AZURE_STORAGE_ACCOUNT=$(AZURE_STORAGE_ACCOUNT)
        - bash: export AZURE_STORAGE_KEY=$(AZURE_STORAGE_KEY)
        - task: Pulumi@1
          displayName: 'Preview'
          inputs:
            azureSubscription: ${{ variables.mysubscription }}
            command: 'preview'
            loginArgs: 'azblob://pulumistatefilecontainer'
            cwd: './'
            stack: 'test'
            createStack: true
        - task: Pulumi@1
          displayName: 'Destroy'
          inputs:
            azureSubscription: ${{ variables.mysubscription }}
            command: 'destroy'
            args: '--yes'
            loginArgs: 'azblob://pulumistatefilecontainer'
            cwd: './'
            stack: 'test'
            createStack: true
        - task: Pulumi@1
          displayName: 'Deploy'
          inputs:
            azureSubscription: ${{ variables.mysubscription }}
            command: 'up'
            args: '--yes'
            loginArgs: 'azblob://pulumistatefilecontainer'
            cwd: './'
            stack: 'test'
            createStack: true            