# Preview Infra
stages:
- stage: PulumiCreateResourceGroup
  jobs:
    - job: infrastructure
      continueOnError: false
      pool:
        vmImage: "ubuntu-latest"
      steps:
        - bash: export PULUMI_CONFIG_PASSPHRASE=$(PULUMI_CONFIG_PASSPHRASE)
        - task: Pulumi@1
          displayName: PulumiPipeline
          inputs:
            command: "up"
            args: "--yes"
            loginArgs: '--local'
            azureSubscription: $(AZURE_SUBSCRIPTION)
            cwd: "./"
            stack: "test"
            createStack: true