# Destroy Resource Group 
stages:
- stage: PulumiPreviewResourceGroup
  jobs:
    - job: InfraStack
      pool:
        vmImage: "ubuntu-latest"
      steps:
        - bash: export PULUMI_CONFIG_PASSPHRASE=$(PULUMI_CONFIG_PASSPHRASE)
        - task: Pulumi@1
          displayName: 'Destroy'
          inputs:
            azureSubscription: 'Pay-As-You-Go(62c557d1-fbce-4f17-a84a-ae68045b0bd6)'
            command: 'destroy'
            loginArgs: '--local'
            cwd: './'
            stack: 'test'
            createStack: true        